### ISSUE TITLE
Create a module that takes an existing Data Package descriptor, and renders its data into the Web Form

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#10]
## Background

We want to support editing of existing Data Package descriptors, as well as the creation of new ones.
## Tasks
- [x] Create a module for rendering a web form with data (this is probably just another module in `datapackage-formbuilder`)
- [x] If the web form currently has user input, and, if the new data from the file will override any of this input, first warn the user
  - Message: "The uploaded file will overwrite some of your existing work. Proceed?"
  - YES - do it
  - NO - revert back to where the user was before uploading 
- [x] Provide an API to re-render the web form with data from a file, when receiving a file (in this case, we receive a file from a user upload action as in #9)
- [x] Write tests for the logic
