### ISSUE TITLE
Create a UI element/workflow that allows a user to add properties and values to the data package that may not have been defined in the Data Package's JSON Schema

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#11]
## Background

Each Data Package Profile has a list of fields: some fields are required, and some are recommended.

Additionally, the Data Package specification allows users to add fields that are not described in a specification: commonly, this means that users will add extra fields on the top-level descriptor, and, on each Resource in the `resources` array.

Example:

```
{
    "name": "some_name",
    "custom_field": "My custom thing",
    "resources": [
        {"name": "resource_name1", "custom_resource_field": "some extra info"},
        {"name": "resource_name1", "custom_resource_field": "some extra info here too"}
    ]
}
```

## Tasks

* [x] Implement UI functionality that allows attaching new fields to the form (anywhere, in theory)
    * User clicks a "+" to add a new field
    * User then gives field a name.
    * All new fields can be simple string input for this implementation, but in future we might want to extend this (user choose input type, for example)
* [x] In the rendered web form, at the bottom of the form, add this ability to extend with new fields
* [x] For each Resource field (ie: the form representation of the resources array), also add the ability to extend the resource with a new field

**Comment by pwalsh** [comment]
I'm going to leave this open in the backlog.

**Comment by pwalsh** [comment]
closing. the built in json-editor functionality is good enough for our use case, and any possible additional will be done as part of #46
