### ISSUE TITLE
UI Tests and related changes in code

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#111]
I've stubbed out a suite of UI tests to complement the unit tests we have in the supporting libraries.

The UI tests use [Zombie.js](http://zombie.js.org/), which in turn requires [io.js](https://iojs.org/en/index.html)

I've created a new branch to facilitate the UI tests: https://github.com/okfn/datapackagist/tree/feature/express

And the test stubs are here: https://github.com/okfn/datapackagist/blob/feature/express/tests/index.js

## Tasks

* [x] Fix any issues when running the app via express instead of gulp/browsersync (on this branch, `npm start` runs the express server, and you can still run `gulp` directly to run the "old" local server)
* [x] Integrate the gulp build + watch tasks with the express server
* [x] Revert the commit that added `#` routing, and adjust the express route handler to work as we'd expect for routing
* [x] Work on the UI test stubs
* [x] Merge back into master

**Comment by gvidon** [comment]
b8e7acb6b2ab7a073958ce2851a480c4011d3ec3
df297722dc889e9f88c00746136093d235b04ec4
5739d0b6114cec44216738adac07290713026dc4
29a11cb97e6b5c7d2622371c21c72d17148e1fcc

**Comment by gvidon** [comment]
ff4d1738b62989648430d018556ac55d62662fcc

**Comment by pwalsh** [comment]
Let's leave it open until all tests pass :).
