### ISSUE TITLE
Modals/Dialogs based on user interaction

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#173]
# Description

# Tasks

* [x] All modal/dialogs should use bootstrap default modals, and pop into the centre of the viewport as they do by default in bootstrap
* [x] Ensure that when a user adds a file to a resource, that we show a loading state
  * [x] Functional tests to ensure it is working
* [x] When a user adds a datapackage.json that is not valid
  * [x] Title: "Invalid File"
  * [x] Body: "The file you added is not a valid data package.json file. Please check and try again"
  * [x] Action: [OK] (closes modal)
* [x] When a user tries to validate resources but the resources array is empty
  * [x] Title: "No Resources to Validate"
  * [x] Body: "The Data Package currently has no resources that can be validated. Please add some and try again."
  * [x] Action: [OK] (closes modal)
* [x] When a user tries to download a datapackage.json but it is invalid
  * [x] Title: "The Data Package Descriptor is invalid"
  * [x] Body: "The Data Package is currently invalid. The following errors have been reported. Fix them and try again. {LIST THE ERRORS NICELY}"
  * [x] Action: [OK] (closes modal)
* [x] When a user tries to validate a datapackage and it is invalid (different action to above, but same result)
  * [x] Title: "The Data Package Descriptor is invalid"
  * [x] Body: "The Data Package is currently invalid. The following errors have been reported. Fix them and try again. {LIST THE ERRORS NICELY}"
  * [x] Action: [OK] (closes modal)
* [x] Functional tests for all these modals
* [x] Are there interactions that I have missed above? Please advise so we can add them
* [x] When a user clicks "how it works"
  * [x] Title: "Data Packagist Documentation"
  * [x] Body: The contents of an MD file, parsed as HTML, called "how-it-works.md" (I'll fill in markdown later)
  * [x] Action: [OK] (closes modal)
* [x] Validation results for file validation in a resource (i.e.: results from GoodTables API) should also be shown in a modal just like the rest of the interactions here.
  * [x] Title: "Data Validation Results"
  * [x] Body: Tabbed data inside the modal (example: http://plnkr.co/edit/Oj681B1YbLU1dJEiWHZp?p=preview)
    * [x] Each tab is dedicated to a resource that has been validated
    * [x] the contents of the tab are the good tables results - if we need to horizontal scroll then do that
    * [x] Each tab "label" shows the name of the resource, and then next to it a tick or a cross from font awesome (example: "budget **x**"). If the validation result for that file has no errors, the icon are is a green tick, and and if there are errors, the icon is a red cross
    * [x] If ALL resources are valid, then do not show the tabs: instead, show a message: "All resources are valid"
  * [x] Action: [OK] (closes modal)
