### ISSUE TITLE
Improved page layout

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#174]
# Description

We want to make user flow clearer, and help users to understand the data they enter. There are a few aspects to this:

* Better base layout of the page
* Layout improvements in the form object itself
* Better flow from the main form to the view that shows validation results of *resources* which is covered in https://github.com/okfn/datapackagist/issues/173
* Better general error messaging, which is covered in https://github.com/okfn/datapackagist/issues/173

# Tasks

* [x] base layout improvements as [documented in this UX Mock](https://docs.google.com/drawings/d/1q3bNCQHCcikPx0lcMGEAw6SCquhzrhqQZKvtCK0om8M/edit)
* [x] layout improvements for the form itself 
  * [x] All help texts in the form can be 11px
  * [x] I'm thinking of having all top-level input fields (anything at top level, except those that render a text area) be split 50/50 (two fields horizontally). This will make the form appear more manageable if we get the size/layout details right. @richhall @gvidon any thoughts on if this could work?
  * [x] Simply remove the properties `dependencies` ("data dependencies"), `resource.dialect`, `contributors`, `sources`, `image`, `base`
    * Can we do this with a property on the schema and not in code? I think we also have other examples of doing this from before.... pls check
  * **TBD**

**Comment by pwalsh** [comment]
@richhall note the updated UX mock here: https://docs.google.com/drawings/d/1q3bNCQHCcikPx0lcMGEAw6SCquhzrhqQZKvtCK0om8M/edit

**Comment by gvidon** [comment]
@pwalsh form fields should be removed in schema profile. Otherwise we will have to remove them in code each time after form rendered or resource added.

**Comment by pwalsh** [comment]
@gvidon no, I can't remove them from the schema profile. What I can do is add a property that you use to not render the field.

**Comment by gvidon** [comment]
I would rather just list these fields in the ```datapackagist``` config and hide them in a code, to keep profile schema clean.

**Comment by pwalsh** [comment]
The config is already not clean - we have various properties there for JSON editor anyway. Please do it from schema - on the hideFromForms property which will be booleqn

**Comment by pwalsh** [comment]
I meant the schema is already not clean

**Comment by pwalsh** [comment]
@gvidon I added an example to the data package schema so you can hook in and test the logic: https://github.com/dataprotocols/schemas/blob/master/data-package.json#L76

**Comment by pwalsh** [comment]
FIXED.
