### ISSUE TITLE
IE9-compatible request library

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#176]
# Description

We need to remove use of superagent, as it does not work in IE9.

Suggested replace is https://github.com/matthew-andrews/isomorphic-fetch, which implements the browser Fetch API, runs in browsers and on Node, and has a polypill that enables support back to IE9.

# Tasks

* [x] Ensure that isomorphic-fetch work in IE9 with some initial tests
* [x] Replace use of superagent with isomorphic-fetch in the following packages:
  * [x] https://github.com/okfn/datapackage-from-remote-js
  * [x] https://github.com/okfn/datapackage-registry-js
  * [x] https://github.com/okfn/goodtables-js
  * [x] And here in DataPackagist
* [x] In DataPackagist, update our dependencies on `datapackage-from-remote` and data package-registry` to the new versions
* [x] Ensure all tests pass on all libs
