### ISSUE TITLE
Optimising resource file (CSV) handling in the client

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#178]
# Description

The CSV handling needs to be optimised so that the app is always only working with a limited size.

There are useful libraries for this, like http://papaparse.com (which is squarely aimed at the browser) and possibly https://github.com/wdavidw/node-csv (which is generally used in Node servers).

I'd suggest using papa parse as it has built-in handling of local and remote files, and a sensible streaming API for CSV.

# Tasks

* [x] This flow should be handling in some higher-level function or something, as we will reuse it in other apps
* [x] Integrate Papa Parse (or other...) into our app for CSV handling
* [x] However we receive CSV, always take a sample of it based on x of lines. Default can be 1000 lines, but this should be configurable by an app-wide setting
  * [x] This means that once we parse a CSV, we only save it up to the sample size we have set. We do not keep the original file around in the browser - we keep our sample
* [x] Clearly, it is the sample that should be (a) sent to `jtsInfer` for processing, and `goodtables` for structure validation
* [x] Write some functional tests for this logic
