### ISSUE TITLE
Refactor data population when adding resources

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#179]
# Description

Some fields do not seem to be populated correctly when adding a data file (which creates a resource in the resources array). We need a clean interface that implements the following correctly. Some of this is working, and some not - just pointing out all the points so that we can get it 100%.

Ideally, we want a distinct function that takes care of this logic when a file is added, so that the function is unit-testable and not directly ties to the json-editor that displays the data.

Obviously when adding a resource, a bunch of other stuff happens too, before the data is written into the form:

1. It is parsed and a sample is taken https://github.com/okfn/datapackagist/issues/178
2. It is validated for structural integrity against the Good Tables API
3. A schema is inferred using JTS Infer

# Tasks

* [x] This logic will need to be added to other apps, so create a wrapping function/container that we can reuse
* [x] IF the file is from a remote source, populate the `resource.url` field with the URL, ELSE IF the file is from a local source, populate the `resource.path` field with the name of the file
  * [x] Never show both `path` and `url`
* [x] The `resource.name` should be extracted from the file name, without the file extension
* [x] The `resource.title` should be generated from the `name`, but as "human readable". there is supposed to be code to track name>title in the codebase (in all places) but it is not working right now
* [x] `resource.format` should be the extension capitalised. e.g.: `file.csv` > `CSV`
* [x] `resource.mediatype` should be to correct mediatype, e.g.: `file.csv` > `text/csv`
* [x] Write tests

**Comment by pwalsh** [comment]
fixed.
