### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#180]
# Description

While the app uses modern web technologies, we want to try to support older versions of Internet Explorer to a point. 

If we can support IE9, we will add appropriate polyfills unless the overall gap is too great. We certainly want to support IE10 and IE11 fully.

# Tasks

* [ ] Confirm status of IE9 support, and possible areas we can polyfill to improve support
* [x] Confirm IE10 support
* [x] Confirm IE11 support

**Comment by borysyuk** [comment]
The project does not support ie9. Problems: 
1. ie9 doesn't support isomorphic-fetch + es6-promise.polyfill
2. ie9 does not support CORS so we should download all resources and files via proxy.
3. goodTables library doesn't work under ie9

I have created new download procedure (using backend) so ie10-11 work fine.

**Comment by pwalsh** [comment]
I'm happy with IE10 and IE11 support. After looking at our whole stack and our goals with the project, IE9 is just lacking too many features to make it a viable support target.
