### ISSUE TITLE
Create a module that reads from a Data Package registry API, and exposes the data

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#2]
## Background

Data Package is a specification for publishing data in simple text files, and for declaring metadata that relates to the data. The [base specification is here](http://dataprotocols.org/data-packages/).

In Data Packages, we have a concept of "Profiles". Profiles are specifications that extend the base specification in particular ways. The most common Profile is "Tabular Data Package". The [specification for Tabular Data Package] is here(http://dataprotocols.org/tabular-data-package/).

We have a Registry for "official" Profiles of Data Package. This registry is currently implemented as a CSV file with required fields. The [registry is here](https://github.com/dataprotocols/registry).

Note that each entry in the Registry has a "schema". This is a URL to a [JSON Schema](http://json-schema.org/) object that describes the structure of each profile. [Here is the JSON Schema for Data Package](https://github.com/dataprotocols/schemas/blob/master/data-package.json).
## Task

We want to be able to read the Data Package Registry and use it in our application. 

So, we want a module that gets the data from the registry, and parses it into a format we can use. This is essentially an API wrapper, and we'll eventually publish this as a standalone module on [npm](http://npmjs.org) as `datapackage-registry`.

I started the basics of this module as part of the skeleton I've provided, in order to demonstrate how browserify works. 

You can use this as a starting point, but feel free to change anything you want. This module, like any others we'll eventually publish to npm, should go directly under `src/components`. [Here it is](https://github.com/okfn/datapackagist/tree/master/admin/src/scripts/components/datapackage-registry).
### Requirements
- [x] Provide a module that can be required in other modules
- [x] Provide a method to get the data as either an array of objects or an array of arrays
- [x] Keep any configurable data in a config object (e.g: the endpoint we call)
- [x] Decide if we are using callbacks or promises or whatever (and we will be consistent with this in all code we write)
- [x] Remove the example console.log stuff I did. Replace it with some small example HTML that outputs the data to the main view
- [x] Write some unit tests that assert the desired functionality
