### ISSUE TITLE
JTSKit for JS

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#28]
## Background

JSON Table Schema is a moving spec, used in Data Package. Recently, we developed [JTSKit](https://github.com/okfn/jtskit-py) in Python, which implemented a significant portion of the JSON Table Schema spec.

There are two older libraries in Javascript: [json-table-schema-infer](https://github.com/okfn/json-table-schema-infer) and [json-table-schema-validator](https://github.com/okfn/json-table-schema-validator). These libraries are not up-to-date with the current state of the JSON Table Schema spec, and and in general, have more holes in their coverage of the spec.

## Goal

Aim for feature parity and API parity between the Python JTSKit, and a new JTSKit for Javascript.

## Tasks

* [x] All code in Node-style JS so we can build a browser version, as well as Node.js support
* [x] Implement types https://github.com/okfn/jtskit-py/blob/master/jtskit/_types.py
* [x] Implement models https://github.com/okfn/jtskit-py/blob/master/jtskit/models.py
* [x] Implement infer https://github.com/okfn/jtskit-py/blob/master/jtskit/infer.py
* [x] test coverage https://github.com/okfn/jtskit-py/tree/master/tests

All code to be done here: https://github.com/okfn/json-table-schema-js

**EDIT**: Removed task that we won't get done in this milestone. They are not on backlog at https://github.com/okfn/json-table-schema-js/issues
