### ISSUE TITLE
Generate a web form from a JSON Schema

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#3]
## Background

As discussed in #2, each Data Package profile has a schema, which is a valid [JSON Schema](http://json-schema.org/). 

The schema provides us with an API to understand (a) all the fields that are described in a Data Package Profile specification (see the [`properties` property](https://github.com/dataprotocols/schemas/blob/master/data-package.json#L6)), and (b) the fields that are _required_ by the specification (see the [`required` property](https://github.com/dataprotocols/schemas/blob/master/data-package.json#L207)).
## Task

<del>Create a new module that generates a form for data input from the structure of a Data Package Profiles's JSON Schema. This should be in a standalone module called `datapackage-formbuilder`.</del>

**Edit:** Someone has already done the hard work for us: https://github.com/jdorn/json-editor

The HTML created by the form builder should use Bootstrap 3 markup. I'm not sure if there are any useful form builder packages available via Node - please check if libraries exist that can help.

<del> 
* [x] Create a new module under `components`
* [x] Implement the logic that introspects a schema and generates for each field name, title, type, required/not required, options, whatever else
* [x] Implement the logic to take the data you've got out of the schema and render it as HTML form elements
* [x] Expose the API for the form builder, so it can be used in our `app.js` (or anywhere)
* [x] Write unit tests for the introspection of the schema, and whatever other logic we have there
</del>
- [x] Check out https://github.com/jdorn/json-editor and see how it works for our needs. It looks very good.
- [x] Render a form for the 'base' Data Package Profile on the main view of the app, as an example

**Note:** If it helps, [I've got a whole bunch of example logic for rendering bootstrap forms here](https://github.com/okfn/goodtables-web/blob/master/web/theme/templates/macros/form.html). This is all implemented as Jinja 2 macros, but should be fairly easy to adapt to whatever you'll use for templating here.
