### ISSUE TITLE
Upload a data file and create a Resource

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#31]
As a user, I want to be able to upload a data file and have it automatically added as a Resource of the Data Package I'm working on.
## Tasks
- [x] Create a new button/action next to the "Resources" section of the form
  - [x] When the user clicks, let the user select a file from her local machine
  - [x] Upload the file and populate a new object in the resources array, with the following properties:
    - [x] name - name of the file as uploaded, with extension
    - [x] path - name of the file as uploaded, with extension
    - [x] schema - the schema as inferred by [jts infer](https://github.com/okfn/json-table-schema-infer)
