### ISSUE TITLE
API wrapper for Good Tables

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#32]
Good Tables is a web service for validating tabular data.

For reference, the code for Good Tables is here:
- https://github.com/okfn/goodtables
- https://github.com/okfn/goodtables-web

And the service itself is currently here:
- http://goodtables.okfnlabs.org/

With API documentation here:
- http://goodtables.okfnlabs.org/api
## Tasks
- [x] Start a new module called "goodtables" under `components`
  - We want to later break this out into a lib on npm
- [x] Provide an interface that wraps the API
  - [x] Expose config of all API options
    - Provide defaults
    - Good Tables supports GET and POST, so we can also allow this as a config option, but default should be GET
  - [x] Provide an easy method for validating a data source, with an optional schema
- [x] Provide a way to handle the results from Good Tables wrapped as a Promise
- [x] Write unit tests for the core logic
