### ISSUE TITLE
Create a UI element that allows a user to select a Data Package Profile, and on selection, renders a form that represents the selected profile

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#4]
## Background

When a user comes to Data Packagist, she wants to work with a Data Package Profile. 

By default on arrival, the 'base' profile is selected, and therefore a form that corresponds to the base profile is displayed. 

The user may want to change the Profile - for example - she actually wants to create a Tabular Data Package. In the case of changing the profile, we'd like to make the experience as smooth as possible for the user, and, if she has already entered some data, to keep what we can when the change is made.
## Task
- [x] Create a selector element that is populated from the Data Package Registry
- [x] With any selection of a Data Package Profile in the selector element, update the form fields as required
- [x] If the user has entered data into the form, ensure that it is persisted on change if possible
  - [x] If a field will be lost when the user changes, first warn the user via a modal
    - Warning message: "Some data you have entered will be lost. Are you sure you want to change the Data Package Profile?"
    - YES - change form and lose data from fields that are lost
    - NO - do not change the form
  - [x] If no fields will be lost in the change (ie: the new Data Package Profile has at least all the same fields that the user has entered data on), then, no need to warn.
