### ISSUE TITLE
UI/UX for displaying validation results

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#45]
<del>Need to flesh this out when #33 is done.</del>

#33 is done. 

## Tasks

* [x] Create a tabbed UI
  * [x] One tab for each resource that has been validated - where the tab shows the validation results for that resource
  * [x] IF only one resource is being validated, THEN do not show tabs
  * **do not** worry about *design of tabs at this stage - the only important thing is the ability to use them to see different validation results
* [x] use the `report_type=grouped` option on the Good Tables API call
  * [x] Add this to our Good Tables javascript library
* [x] Port over the CSS and HTML for the results from the Good Tables web service - see links below
  * [x] Port the HTML/logic for each "result group"
  * Don't port other elements at this stage - let's check in when it gets this far, and discuss further.

**Comment by pwalsh** [comment]
We basically want to implement a version of the reports displayed on good tables web service when using the UI. That UI uses the same base "app theme", and has a few extra classes for the report [display here](https://github.com/okfn/goodtables-web/blob/master/web/theme/static/css/custom.scss)

* [Here is an example of that UI](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json)

* [Here is an example API call for the same results](http://goodtables.okfnlabs.org/api/run?format=csv&row_limit=20000&schema=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json&report_limit=1000&data=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&report_type=grouped)

**Comment by gvidon** [comment]
https://github.com/okfn/goodtables-js/pull/4

**Comment by pwalsh** [comment]
@gvidon from a quick play with the UI and look at the code - it looks very good!

I have a bug though - it seems the schema being sent to good tables is not the schema of the file that is being validated. 

Example: I add a resource with fields "id" and "amount", and yet the good tables validation says that my data headers are incorrect - that I should have "name, url, path, format, mediatype, encoding, bytes, hash, schema, dialect, sources, licences". Note that these are all the keys from the Resource object, but the schema that is sent to good tables should be the Resource.schema.

**Comment by gvidon** [comment]
@pwalsh ok, will take a look

**Comment by alexeyk** [comment]
@gvidon I'm checking it, shuld be done in few hours.
